### ISSUE TITLE
Cannot run jbundle install for hellowarld

### ISSUE THREAD

**Issue by rtyler** [lookout/leafy#25]
Trying to figure out and isolate the TravisCI failures in #24 and I'm getting the following exception which doesn't look right to me :/

```
➜  hellowarld git:(master) ✗ jbundle install
Resolving dependencies...
Using rake 10.4.2
Using thread_safe 0.3.4
Using descendants_tracker 0.0.4
Using ice_nine 0.11.1
Using axiom-types 0.1.1
Using coercible 1.0.0
Using equalizer 0.0.9
Using jar-dependencies 0.1.8
  jar dependencies for leafy-health-0.1.0.gemspec . . .
      io.dropwizard.metrics:metrics-healthchecks:3.1.0
      io.dropwizard.metrics:metrics-jvm:3.1.0
Using leafy-health 0.1.0 from source at ../../leafy-health
  jar dependencies for leafy-metrics-0.1.0.gemspec . . .

RuntimeError: can not assign such an array ["org.slf4j", "slf4j-simple", "1.7.7", "(", "scope=", "test-SNAPSHOT,)"]
             fill_gav at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1479
  retrieve_dependency at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1096
        do_dependency at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1117
          _dependency at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1050
                 spec at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:442
                 each at org/jruby/RubyArray.java:1613
                 spec at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:441
              gemspec at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:378
             eval_pom at /home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/jar-dependencies-0.1.8/lib/jars/jar_pom.rb:10
                 call at org/jruby/RubyProc.java:271
         nested_block at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1450
                tesla at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:20
             eval_pom at /home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/jar-dependencies-0.1.8/lib/jars/jar_pom.rb:1
                 eval at org/jruby/RubyKernel.java:1101
             eval_pom at file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:51
                parse at parser.rb:74
[ERROR] Internal error: org.jruby.embed.InvokeFailedException: (RuntimeError) can not assign such an array ["org.slf4j", "slf4j-simple", "1.7.7", "(", "scope=", "test-SNAPSHOT,)"] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.jruby.embed.InvokeFailedException: (RuntimeError) can not assign such an array ["org.slf4j", "slf4j-simple", "1.7.7", "(", "scope=", "test-SNAPSHOT,)"]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:164)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.PolyglotMavenCli.main(PolyglotMavenCli.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.jruby.embed.InvokeFailedException: (RuntimeError) can not assign such an array ["org.slf4j", "slf4j-simple", "1.7.7", "(", "scope=", "test-SNAPSHOT,)"]
	at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.call(EmbedRubyObjectAdapterImpl.java:317)
	at org.jruby.embed.internal.EmbedRubyObjectAdapterImpl.callMethod(EmbedRubyObjectAdapterImpl.java:169)
	at org.jruby.embed.ScriptingContainer.callMethod(ScriptingContainer.java:1432)
	at org.sonatype.maven.polyglot.ruby.RubyParser.parse(RubyParser.java:66)
	at org.sonatype.maven.polyglot.ruby.RubyModelReader.read(RubyModelReader.java:63)
	at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:136)
	at org.sonatype.maven.polyglot.TeslaModelProcessor.read(TeslaModelProcessor.java:86)
	at org.apache.maven.model.building.DefaultModelBuilder.readModel(DefaultModelBuilder.java:453)
	at org.apache.maven.model.building.DefaultModelBuilder.build(DefaultModelBuilder.java:256)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:411)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:380)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:344)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:637)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:586)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:229)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
	... 11 more
Caused by: org.jruby.exceptions.RaiseException: (RuntimeError) can not assign such an array ["org.slf4j", "slf4j-simple", "1.7.7", "(", "scope=", "test-SNAPSHOT,)"]
	at RUBY.fill_gav(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1479)
	at RUBY.retrieve_dependency(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1096)
	at RUBY.do_dependency(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1117)
	at RUBY._dependency(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1050)
	at RUBY.spec(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:442)
	at org.jruby.RubyArray.each(org/jruby/RubyArray.java:1613)
	at RUBY.spec(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:441)
	at RUBY.gemspec(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:378)
	at RUBY.eval_pom(/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/jar-dependencies-0.1.8/lib/jars/jar_pom.rb:10)
	at org.jruby.RubyProc.call(org/jruby/RubyProc.java:271)
	at RUBY.nested_block(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:1450)
	at RUBY.tesla(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:20)
	at RUBY.eval_pom(/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/jar-dependencies-0.1.8/lib/jars/jar_pom.rb:1)
	at org.jruby.RubyKernel.eval(org/jruby/RubyKernel.java:1101)
	at RUBY.eval_pom(file:/home/tyler/.rvm/gems/jruby-1.7.19@rubygems/gems/ruby-maven-3.1.1.0.9/ruby-maven-home/ext/ruby/tesla-polyglot-ruby-0.1.1.jar!/maven/tools/dsl.rb:51)
	at RUBY.parse(parser.rb:74)
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException


Errno::ENOENT: No such file or directory - /home/tyler/source/github/ruby/leafy/leafy-metrics/deps.lst
An error occurred while installing leafy-metrics (0.1.0), and Bundler cannot
continue.
Make sure that `gem install leafy-metrics -v '0.1.0'` succeeds before bundling.
➜  hellowarld git:(master) ✗ 

```

**Comment by mkristian** [comment]
looking . . .

**Comment by mkristian** [comment]
travis does not use jbundler and the Jarfile.lock is only needed pack a warfile later on. and this is not part of travis run at all. feels like this bug is beyond the scope of leafy - just removing jbundler stuff now.

**Comment by mkristian** [comment]
fixed via https://github.com/lookout/leafy/commit/ba0e779955b06a79e00f963f1ebc5f58c40ae6d4 - no more jbundler
